<?php
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
function adb(){static $p;if($p)return $p;$p=new PDO('mysql:host='.(getenv('DB_HOST')?:'127.0.0.1').';port='.(getenv('DB_PORT')?:'3306').';dbname='.(getenv('DB_NAME')?:'datasell').';charset=utf8mb4',getenv('DB_USER')?:'root',getenv('DB_PASS')?:'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);return $p;}function out($d,$c=200){http_response_code($c);echo json_encode($d,JSON_UNESCAPED_SLASHES);exit;}function body(){return json_decode(file_get_contents('php://input'),true)?:[];}function bearer(){if(!preg_match('/Bearer\s+(.+)/i',$_SERVER['HTTP_AUTHORIZATION']??'', $m))return null;return trim($m[1]);}
try{$db=adb();$db->exec("CREATE TABLE IF NOT EXISTS mobile_tokens(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at DATETIME NOT NULL,last_used_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id),INDEX(expires_at)) ENGINE=InnoDB");if(is_file(__DIR__.'/platform-upgrade.php')){require_once __DIR__.'/platform-upgrade.php';ih_platform_upgrade($db);}}catch(Throwable $e){out(['ok'=>false,'error'=>'Service unavailable'],503);}
$path=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');$path=preg_replace('#^api-v1\.php/?#','',$path);$method=$_SERVER['REQUEST_METHOD']??'GET';
if($method==='GET'&&($path===''||$path==='health'))out(['ok'=>true,'service'=>'IHLink Datasub API','version'=>'v1','provider_live'=>getenv('PROVIDER_LIVE')==='1']);
if($method==='POST'&&$path==='login'){$b=body();$q=$db->prepare('SELECT id,fullname,email,password_hash FROM users WHERE LOWER(email)=?');$q->execute([strtolower(trim($b['email']??''))]);$u=$q->fetch();if(!$u||!password_verify($b['password']??'',$u['password_hash']))out(['ok'=>false,'error'=>'Invalid credentials'],401);$token=bin2hex(random_bytes(32));$db->prepare('INSERT INTO mobile_tokens(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 30 DAY))')->execute([$u['id'],hash('sha256',$token)]);out(['ok'=>true,'token'=>$token,'user'=>['id'=>(int)$u['id'],'fullname'=>$u['fullname'],'email'=>$u['email']]]);}
$token=bearer();if(!$token)out(['ok'=>false,'error'=>'Authentication required'],401);$q=$db->prepare('SELECT mt.id token_id,u.id,u.fullname,u.email,u.phone,u.wallet_balance,u.account_type,u.customer_tier FROM mobile_tokens mt JOIN users u ON u.id=mt.user_id WHERE mt.token_hash=? AND mt.expires_at>NOW()');$q->execute([hash('sha256',$token)]);$u=$q->fetch();if(!$u)out(['ok'=>false,'error'=>'Invalid or expired token'],401);$db->prepare('UPDATE mobile_tokens SET last_used_at=NOW() WHERE id=?')->execute([$u['token_id']]);
if($method==='POST'&&$path==='logout'){$db->prepare('DELETE FROM mobile_tokens WHERE id=?')->execute([$u['token_id']]);out(['ok'=>true]);}
if($method==='GET'&&$path==='me')out(['ok'=>true,'user'=>['id'=>(int)$u['id'],'fullname'=>$u['fullname'],'email'=>$u['email'],'phone'=>$u['phone'],'balance'=>(float)$u['wallet_balance'],'account_type'=>$u['account_type'],'tier'=>$u['customer_tier']]]);
if($method==='GET'&&$path==='products'){$cat=trim($_GET['category']??'');$sql='SELECT id,category,provider,name,code,retail_price,premium_price,reseller_price,api_price,face_value,validity,plan_type FROM service_plans WHERE active=1';$args=[];if($cat!==''){$sql.=' AND category=?';$args[]=$cat;}$sql.=' ORDER BY category,sort_order,id';$q=$db->prepare($sql);$q->execute($args);$rows=$q->fetchAll();foreach($rows as &$r){$tier=$u['customer_tier']??'standard';$r['price']=(float)($u['account_type']==='api'?$r['api_price']:($u['account_type']==='reseller'?$r['reseller_price']:($tier==='premium'&&$r['premium_price']>0?$r['premium_price']:$r['retail_price'])));unset($r['retail_price'],$r['premium_price'],$r['reseller_price'],$r['api_price']);}out(['ok'=>true,'products'=>$rows]);}
if($method==='GET'&&$path==='transactions'){$q=$db->prepare('SELECT id,type,amount,status,reference,details,created_at FROM transactions WHERE user_id=? ORDER BY id DESC LIMIT 100');$q->execute([$u['id']]);out(['ok'=>true,'transactions'=>$q->fetchAll()]);}
if($method==='GET'&&$path==='beneficiaries'){$q=$db->prepare('SELECT id,label,recipient,service_type,provider,created_at FROM beneficiaries WHERE user_id=? ORDER BY id DESC');$q->execute([$u['id']]);out(['ok'=>true,'beneficiaries'=>$q->fetchAll()]);}
if($method==='POST'&&$path==='beneficiaries'){$b=body();$recipient=trim($b['recipient']??'');$type=trim($b['service_type']??'');if($recipient===''||$type==='')out(['ok'=>false,'error'=>'Recipient and service type are required'],422);$q=$db->prepare('INSERT INTO beneficiaries(user_id,label,recipient,service_type,provider) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),provider=VALUES(provider)');$q->execute([$u['id'],trim($b['label']??'')?:null,$recipient,$type,trim($b['provider']??'')?:null]);out(['ok'=>true],201);}
if($method==='GET'&&$path==='notifications'){$q=$db->prepare('SELECT id,title,message,type,read_at,created_at FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 100');$q->execute([$u['id']]);out(['ok'=>true,'notifications'=>$q->fetchAll()]);}
out(['ok'=>false,'error'=>'Endpoint not found'],404);