<?php
session_start();
function db(){static $p=null;if($p)return $p;$h=getenv('DB_HOST')?:'127.0.0.1';$pt=getenv('DB_PORT')?:'3306';$n=getenv('DB_NAME')?:'datasell';$u=getenv('DB_USER')?:'root';$pw=getenv('DB_PASS')?:'';$p=new PDO("mysql:host=$h;port=$pt;dbname=$n;charset=utf8mb4",$u,$pw,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);return $p;}
function initdb(){try{$p=db();$p->exec("CREATE TABLE IF NOT EXISTS users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,fullname VARCHAR(120) NOT NULL,email VARCHAR(160) NOT NULL UNIQUE,phone VARCHAR(20) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,wallet_balance DECIMAL(14,2) NOT NULL DEFAULT 0,is_admin TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;CREATE TABLE IF NOT EXISTS transactions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,type VARCHAR(50) NOT NULL,amount DECIMAL(14,2) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'successful',reference VARCHAR(80) NOT NULL UNIQUE,details TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id)) ENGINE=InnoDB;CREATE TABLE IF NOT EXISTS funding_requests(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,amount DECIMAL(14,2) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',reference VARCHAR(80) NOT NULL UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB");}catch(Throwable $e){return false;}return true;}initdb();
function me(){if(empty($_SESSION['uid']))return null;$s=db()->prepare('SELECT id,fullname,email,phone,wallet_balance,is_admin FROM users WHERE id=?');$s->execute([$_SESSION['uid']]);return $s->fetch();}
function ref($p='TX'){return $p.'-'.date('YmdHis').'-'.strtoupper(bin2hex(random_bytes(3)));}
function esc($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$action=$_POST['action']??'';$msg='';$err='';
try{
if($action==='register'){if(strlen($_POST['password']??'')<6)throw new Exception('Password must be at least 6 characters.');$s=db()->prepare('INSERT INTO users(fullname,email,phone,password_hash) VALUES(?,?,?,?)');$s->execute([trim($_POST['fullname']),strtolower(trim($_POST['email'])),preg_replace('/\D/','',$_POST['phone']),password_hash($_POST['password'],PASSWORD_DEFAULT)]);$_SESSION['uid']=db()->lastInsertId();header('Location: ?page=dashboard');exit;}
if($action==='login'){$s=db()->prepare('SELECT * FROM users WHERE email=?');$s->execute([strtolower(trim($_POST['email']))]);$u=$s->fetch();if(!$u||!password_verify($_POST['password'],$u['password_hash']))throw new Exception('Invalid email or password.');$_SESSION['uid']=$u['id'];header('Location: ?page=dashboard');exit;}
if($action==='logout'){session_destroy();header('Location: /');exit;}
if($action==='fund'){if(!me())throw new Exception('Please sign in.');$a=(float)$_POST['amount'];if($a<100)throw new Exception('Minimum funding request is ₦100.');db()->prepare('INSERT INTO funding_requests(user_id,amount,reference) VALUES(?,?,?)')->execute([me()['id'],$a,ref('FUND')]);$msg='Funding request submitted for admin verification.';}
if($action==='buy'){if(!me())throw new Exception('Please sign in.');$a=(float)$_POST['amount'];$u=me();if($a<=0||$a>$u['wallet_balance'])throw new Exception('Insufficient wallet balance.');$type=$_POST['type']??'service';$p=db();$p->beginTransaction();$p->prepare('UPDATE users SET wallet_balance=wallet_balance-? WHERE id=?')->execute([$a,$u['id']]);$p->prepare('INSERT INTO transactions(user_id,type,amount,status,reference,details) VALUES(?,?,?,?,?,?)')->execute([$u['id'],$type,$a,'successful',ref(),json_encode(['provider'=>$_POST['provider']??'','recipient'=>$_POST['recipient']??''])]);$p->commit();$msg='Demo transaction recorded successfully. Live fulfillment requires a provider API.';}
if($action==='approve'&&me()&&me()['is_admin']){$id=(int)$_POST['id'];$p=db();$p->beginTransaction();$s=$p->prepare("SELECT * FROM funding_requests WHERE id=? AND status='pending' FOR UPDATE");$s->execute([$id]);$r=$s->fetch();if(!$r)throw new Exception('Request not found.');$p->prepare("UPDATE funding_requests SET status='approved' WHERE id=?")->execute([$id]);$p->prepare('UPDATE users SET wallet_balance=wallet_balance+? WHERE id=?')->execute([$r['amount'],$r['user_id']]);$p->prepare('INSERT INTO transactions(user_id,type,amount,status,reference) VALUES(?,?,?,?,?)')->execute([$r['user_id'],'wallet_funding',$r['amount'],'successful',$r['reference']]);$p->commit();$msg='Wallet funded successfully.';}
}catch(Throwable $e){$err=$e->getMessage();}
$page=$_GET['page']??'home';$u=me();if(in_array($page,['dashboard','data','airtime','bills','exam','wallet','transactions','profile','admin'])&&!$u){header('Location: ?page=login');exit;}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DataSell</title><style>
:root{--p:#4f46e5;--dark:#0f172a;--bg:#f8fafc;--muted:#64748b;--line:#e2e8f0}*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:var(--bg);color:var(--dark)}a{text-decoration:none;color:inherit}.top{height:70px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 6%}.brand{font-size:24px;font-weight:900;color:var(--p)}.nav{display:flex;gap:20px;align-items:center}.btn{border:0;border-radius:10px;padding:12px 18px;font-weight:700;cursor:pointer}.primary{background:var(--p);color:white}.secondary{background:#eef2ff;color:var(--p)}.hero{padding:90px 6%;display:grid;grid-template-columns:1.2fr .8fr;gap:50px;align-items:center;background:linear-gradient(135deg,#eef2ff,#fff)}h1{font-size:50px;line-height:1.05;margin:12px 0}p{color:var(--muted);line-height:1.7}.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:24px;box-shadow:0 8px 30px #0f172a0d}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.section{padding:55px 6%}.app{display:grid;grid-template-columns:250px 1fr;min-height:100vh}.side{background:var(--dark);color:#cbd5e1;padding:28px 18px}.side .brand{color:#fff;margin-bottom:30px}.side a{display:block;padding:12px;border-radius:9px;margin:4px 0}.side a:hover{background:#1e293b;color:#fff}.main{padding:34px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:22px 0}.value{font-size:28px;font-weight:900;margin-top:8px}.form{max-width:650px}.input{width:100%;padding:13px;border:1px solid var(--line);border-radius:9px;margin:7px 0 16px;font-size:15px}.alert{padding:12px 15px;border-radius:9px;margin-bottom:16px;background:#ecfdf5;color:#047857}.error{background:#fef2f2;color:#b91c1c}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:12px;border-bottom:1px solid var(--line);font-size:14px}.auth{max-width:430px;margin:70px auto}.service{cursor:pointer}.service b{display:block;font-size:18px;margin:8px 0}.badge{display:inline-block;background:#dcfce7;color:#166534;padding:7px 10px;border-radius:20px;font-weight:700;font-size:13px}@media(max-width:800px){.hero,.app{grid-template-columns:1fr}.side{display:none}.grid,.stats{grid-template-columns:1fr 1fr}h1{font-size:38px}.nav a:not(.btn){display:none}.main{padding:20px}}@media(max-width:480px){.grid,.stats{grid-template-columns:1fr}}
</style></head><body>
<?php if($page==='home'):?><header class="top"><div class="brand">DataSell</div><nav class="nav"><a href="#services">Services</a><a href="?page=api">API</a><a href="?page=login">Login</a><a class="btn primary" href="?page=register">Create account</a></nav></header><section class="hero"><div><span class="badge">Fast • Simple • Secure</span><h1>One wallet for data, airtime and everyday bills.</h1><p>Buy mobile data and airtime, manage utility payments, exam pins, wallet funding and transaction history from one responsive platform.</p><a class="btn primary" href="?page=register">Get started</a></div><div class="card"><p>Available balance</p><div class="value">₦24,850.00</div><p>Demo wallet preview</p></div></section><section class="section" id="services"><h2>Everything you need</h2><div class="grid"><?php foreach(['Mobile Data','Airtime','Electricity','Cable TV','Exam Pins','Airtime to Cash','Reseller API','Transactions'] as $x):?><div class="card service"><b><?=esc($x)?></b><p>Managed from your secure DataSell dashboard.</p></div><?php endforeach?></div></section>
<?php elseif($page==='login'||$page==='register'):?><header class="top"><a class="brand" href="/">DataSell</a></header><div class="auth card"><h2><?=$page==='login'?'Sign in':'Create account'?></h2><?php if($err):?><div class="alert error"><?=esc($err)?></div><?php endif?><form method="post"><input type="hidden" name="action" value="<?=$page?>"><?php if($page==='register'):?><label>Full name</label><input class="input" name="fullname" required><label>Phone</label><input class="input" name="phone" required><?php endif?><label>Email</label><input class="input" name="email" type="email" required><label>Password</label><input class="input" name="password" type="password" minlength="6" required><button class="btn primary" style="width:100%"><?=$page==='login'?'Login':'Create account'?></button></form><p><?=$page==='login'?'No account? <a href="?page=register">Register</a>':'Already registered? <a href="?page=login">Sign in</a>'?></p></div>
<?php elseif($page==='api'):?><header class="top"><a class="brand" href="/">DataSell API</a></header><section class="section"><div class="card"><h1 style="font-size:36px">Reseller API</h1><p>API-ready architecture for external resellers. Production API keys, HMAC signing, rate limits and live provider settlement will be enabled when provider credentials are configured.</p><pre>POST /api/v1/data/purchase
POST /api/v1/airtime/purchase
GET  /api/v1/transactions/{reference}</pre></div></section>
<?php else:?><div class="app"><aside class="side"><div class="brand">DataSell</div><?php foreach(['dashboard'=>'Overview','data'=>'Buy Data','airtime'=>'Airtime','bills'=>'Bills','exam'=>'Exam Pins','wallet'=>'Fund Wallet','transactions'=>'Transactions','profile'=>'Profile'] as $k=>$v):?><a href="?page=<?=$k?>"><?=$v?></a><?php endforeach?><?php if($u['is_admin']):?><a href="?page=admin">Admin</a><?php endif?><form method="post"><input type="hidden" name="action" value="logout"><button class="btn secondary" style="margin-top:20px">Logout</button></form></aside><main class="main"><h2><?=esc(ucwords(str_replace('-',' ',$page)))?></h2><?php if($msg):?><div class="alert"><?=esc($msg)?></div><?php endif?><?php if($err):?><div class="alert error"><?=esc($err)?></div><?php endif?>
<?php if($page==='dashboard'):?><p>Welcome back, <?=esc($u['fullname'])?>.</p><div class="stats"><div class="card"><span>Wallet balance</span><div class="value">₦<?=number_format($u['wallet_balance'],2)?></div></div><div class="card"><span>Account</span><div class="value"><?=$u['is_admin']?'Admin':'Customer'?></div></div><div class="card"><span>Status</span><div class="value">Active</div></div></div><div class="grid"><?php foreach(['data'=>'Buy Data','airtime'=>'Airtime','bills'=>'Pay Bills','exam'=>'Exam Pins','wallet'=>'Fund Wallet','transactions'=>'History'] as $k=>$v):?><a class="card service" href="?page=<?=$k?>"><b><?=$v?></b><p>Open service</p></a><?php endforeach?></div>
<?php elseif(in_array($page,['data','airtime','bills','exam'])):?><div class="card form"><p>This purchase is recorded locally. Connect your live VTU/bill provider API before accepting real customer orders.</p><form method="post"><input type="hidden" name="action" value="buy"><input type="hidden" name="type" value="<?=esc($page)?>"><label>Provider / Network</label><select class="input" name="provider"><?php foreach($page==='data'||$page==='airtime'?['MTN','AIRTEL','GLO','9MOBILE']:($page==='exam'?['WAEC','NECO','NABTEB']:['Electricity','DStv','GOtv','StarTimes']) as $x):?><option><?=esc($x)?></option><?php endforeach?></select><label>Phone / Meter / Smartcard</label><input class="input" name="recipient" required><label>Amount (₦)</label><input class="input" type="number" name="amount" min="1" required><button class="btn primary">Submit purchase</button></form></div>
<?php elseif($page==='wallet'):?><div class="card form"><p>Funding currently uses admin verification. Paystack can be enabled after production keys are supplied securely.</p><form method="post"><input type="hidden" name="action" value="fund"><label>Amount (₦)</label><input class="input" type="number" name="amount" min="100" required><button class="btn primary">Submit funding request</button></form></div>
<?php elseif($page==='transactions'):$s=db()->prepare('SELECT * FROM transactions WHERE user_id=? ORDER BY id DESC LIMIT 100');$s->execute([$u['id']]);?><div class="card" style="overflow:auto"><table class="table"><tr><th>Type</th><th>Amount</th><th>Status</th><th>Reference</th><th>Date</th></tr><?php foreach($s as $t):?><tr><td><?=esc($t['type'])?></td><td>₦<?=number_format($t['amount'],2)?></td><td><?=esc($t['status'])?></td><td><?=esc($t['reference'])?></td><td><?=esc($t['created_at'])?></td></tr><?php endforeach?></table></div>
<?php elseif($page==='profile'):?><div class="card form"><p><b><?=esc($u['fullname'])?></b></p><p><?=esc($u['email'])?></p><p><?=esc($u['phone'])?></p></div>
<?php elseif($page==='admin'&&$u['is_admin']):$rs=db()->query("SELECT f.*,u.email FROM funding_requests f JOIN users u ON u.id=f.user_id ORDER BY f.id DESC LIMIT 100");?><div class="card" style="overflow:auto"><h3>Funding requests</h3><table class="table"><tr><th>User</th><th>Amount</th><th>Status</th><th>Action</th></tr><?php foreach($rs as $r):?><tr><td><?=esc($r['email'])?></td><td>₦<?=number_format($r['amount'],2)?></td><td><?=esc($r['status'])?></td><td><?php if($r['status']==='pending'):?><form method="post"><input type="hidden" name="action" value="approve"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn primary">Approve</button></form><?php endif?></td></tr><?php endforeach?></table></div><?php endif?></main></div><?php endif?></body></html>