<?php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
function sa_db(){static $p=null;if($p)return $p;$p=new PDO('mysql:host='.(getenv('DB_HOST')?:'127.0.0.1').';port='.(getenv('DB_PORT')?:'3306').';dbname='.(getenv('DB_NAME')?:'datasell').';charset=utf8mb4',getenv('DB_USER')?:'root',getenv('DB_PASS')?:'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);return $p;}
function se($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function scsrf(){if(empty($_SESSION['staff_csrf']))$_SESSION['staff_csrf']=bin2hex(random_bytes(24));return $_SESSION['staff_csrf'];}
function scheck(){if(!hash_equals($_SESSION['staff_csrf']??'',$_POST['csrf']??''))throw new Exception('Session expired. Refresh and try again.');}
function sme(){if(empty($_SESSION['uid']))return null;$q=sa_db()->prepare('SELECT id,fullname,email,admin_role FROM users WHERE id=?');$q->execute([$_SESSION['uid']]);return $q->fetch()?:null;}
$roles=[
 'general_admin'=>['General Admin',['users','transactions','funding','products','upgrades','resellers','api_users','reports']],
 'finance_admin'=>['Finance Admin',['transactions','funding','reports']],
 'support_admin'=>['Support Admin',['users','transactions','upgrades','resellers']],
 'product_admin'=>['Product / Pricing Admin',['products','reports']],
 'technical_admin'=>['Technical / API Admin',['api_users','resellers','reports']]
];
$permLabels=['users'=>'Users & Accounts','transactions'=>'Transactions','funding'=>'Wallet Funding','products'=>'Products & Pricing','upgrades'=>'Upgrade Requests','resellers'=>'Resellers','api_users'=>'API Users','reports'=>'Reports'];
$p=sa_db();
try{
 $cols=$p->query('SHOW COLUMNS FROM users')->fetchAll(PDO::FETCH_COLUMN);
 if(!in_array('staff_role',$cols,true))$p->exec("ALTER TABLE users ADD staff_role VARCHAR(40) NULL AFTER admin_role");
 if(!in_array('admin_permissions',$cols,true))$p->exec("ALTER TABLE users ADD admin_permissions TEXT NULL AFTER staff_role");
 if(!in_array('admin_enabled',$cols,true))$p->exec("ALTER TABLE users ADD admin_enabled TINYINT(1) NOT NULL DEFAULT 1 AFTER admin_permissions");
 $p->exec("CREATE TABLE IF NOT EXISTS admin_audit_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,admin_user_id INT UNSIGNED NOT NULL,action VARCHAR(100) NOT NULL,target_user_id INT UNSIGNED NULL,details TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(admin_user_id),INDEX(target_user_id),INDEX(created_at)) ENGINE=InnoDB");
}catch(Throwable $x){}
$me=sme();if(!$me){header('Location:/?page=login');exit;}if($me['admin_role']!=='super_admin'){header('Location:/?page=dashboard');exit;}
$msg='';$err='';
try{if($_SERVER['REQUEST_METHOD']==='POST'){scheck();$action=$_POST['action']??'';
 if($action==='assign_staff'){
  $uid=(int)($_POST['user_id']??0);$role=$_POST['staff_role']??'';
  if(!isset($roles[$role]))throw new Exception('Invalid staff role.');
  $target=$p->prepare('SELECT id,email,admin_role FROM users WHERE id=?');$target->execute([$uid]);$target=$target->fetch();if(!$target)throw new Exception('User not found.');if($target['admin_role']==='super_admin')throw new Exception('Super Admin permissions cannot be changed here.');
  $allowed=array_keys($permLabels);$chosen=array_values(array_intersect($allowed,$_POST['permissions']??[]));if(!$chosen)$chosen=$roles[$role][1];
  $p->prepare("UPDATE users SET is_admin=1,admin_role='admin',staff_role=?,admin_permissions=?,admin_enabled=1 WHERE id=?")->execute([$role,json_encode($chosen),$uid]);
  $p->prepare('INSERT INTO admin_audit_logs(admin_user_id,action,target_user_id,details) VALUES(?,?,?,?)')->execute([$me['id'],'staff_admin_assigned',$uid,json_encode(['role'=>$role,'permissions'=>$chosen])]);$msg='Staff administrator assigned successfully.';
 }
 if($action==='disable_staff'){
  $uid=(int)($_POST['user_id']??0);$p->prepare("UPDATE users SET admin_enabled=0,is_admin=0,admin_role='none' WHERE id=? AND admin_role<>'super_admin'")->execute([$uid]);
  $p->prepare('INSERT INTO admin_audit_logs(admin_user_id,action,target_user_id,details) VALUES(?,?,?,?)')->execute([$me['id'],'staff_admin_disabled',$uid,'{}']);$msg='Staff administrative access disabled.';
 }
 if($action==='enable_staff'){
  $uid=(int)($_POST['user_id']??0);$q=$p->prepare('SELECT staff_role FROM users WHERE id=?');$q->execute([$uid]);$sr=$q->fetchColumn();if(!$sr||!isset($roles[$sr]))throw new Exception('Assign a staff role first.');$p->prepare("UPDATE users SET admin_enabled=1,is_admin=1,admin_role='admin' WHERE id=?")->execute([$uid]);
  $p->prepare('INSERT INTO admin_audit_logs(admin_user_id,action,target_user_id,details) VALUES(?,?,?,?)')->execute([$me['id'],'staff_admin_enabled',$uid,'{}']);$msg='Staff administrative access enabled.';
 }
}}catch(Throwable $x){$err=$x->getMessage();}
$csrf=scsrf();$users=$p->query("SELECT id,fullname,email,admin_role,staff_role,admin_permissions,admin_enabled,created_at FROM users ORDER BY CASE WHEN admin_role='super_admin' THEN 0 WHEN admin_role='admin' THEN 1 ELSE 2 END,id DESC LIMIT 300")->fetchAll();
$logs=$p->query("SELECT l.*,u.fullname admin_name,t.fullname target_name FROM admin_audit_logs l LEFT JOIN users u ON u.id=l.admin_user_id LEFT JOIN users t ON t.id=l.target_user_id ORDER BY l.id DESC LIMIT 100")->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IHLink Datasub — Staff Administration</title><link rel="stylesheet" href="/assets/css/app.css?v=7"><style>body{background:#f5f7fb}.wrap{max-width:1450px;margin:auto;padding:28px}.head{display:flex;justify-content:space-between;gap:18px;align-items:center}.panel{background:#fff;border:1px solid #e3e9f0;border-radius:18px;padding:22px;margin:20px 0;overflow:auto}.notice{padding:12px;border-radius:10px}.ok{background:#eaf8f0;color:#137a4a}.bad{background:#fff0f0;color:#a62929}.table{width:100%;border-collapse:collapse;min-width:1050px}.table th,.table td{padding:12px;border-bottom:1px solid #edf1f5;text-align:left;vertical-align:top}.table th{font-size:11px;text-transform:uppercase;color:#748095}.badge{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eef2f6;font-size:11px;font-weight:800}.super{background:#eee7ff;color:#6841c6}.admin{background:#e8f2ff;color:#1469b8}.disabled{background:#fff0f0;color:#a62929}.form-grid{display:grid;grid-template-columns:220px 1fr auto;gap:10px;align-items:start}.perms{display:flex;gap:8px 14px;flex-wrap:wrap}.perms label{font-size:12px}.btnx{border:0;border-radius:9px;padding:9px 12px;background:#0b6bcb;color:#fff;font-weight:800;cursor:pointer}.danger{background:#fff0f0;color:#a62929}.muted{font-size:12px;color:#6d7b8e}@media(max-width:800px){.wrap{padding:15px}.head{align-items:flex-start;flex-direction:column}.form-grid{grid-template-columns:1fr}}</style></head><body><main class="wrap"><header class="head"><div><span class="eyebrow">Super Admin</span><h1>Staff Admin Management</h1><p class="muted">Create controlled staff access without sharing your Super Admin account.</p></div><div><a class="btn btn-ghost" href="/admin-control.php">Tier Management</a> <a class="btn btn-primary" href="/?page=admin">Admin Console</a></div></header><?php if($msg):?><div class="notice ok"><?=se($msg)?></div><?php endif;?><?php if($err):?><div class="notice bad"><?=se($err)?></div><?php endif;?>
<section class="panel"><h2>Users & staff administrators</h2><p class="muted">A staff member first registers a normal IHLink account. You then assign a staff role and permissions here. Only you can manage this page.</p><table class="table"><thead><tr><th>User</th><th>Current access</th><th>Staff role & permissions</th><th>Control</th></tr></thead><tbody><?php foreach($users as $u):$current=json_decode($u['admin_permissions']?:'[]',true)?:[];?><tr><td><b><?=se($u['fullname'])?></b><br><span class="muted"><?=se($u['email'])?></span></td><td><?php if($u['admin_role']==='super_admin'):?><span class="badge super">Super Admin</span><?php elseif($u['admin_role']==='admin'):?><span class="badge admin">Admin</span><?php else:?><span class="badge <?=$u['staff_role']&&!$u['admin_enabled']?'disabled':''?>"><?=$u['staff_role']&&!$u['admin_enabled']?'Disabled':'No admin'?></span><?php endif;?></td><td><?php if($u['admin_role']==='super_admin'):?>Full platform authority<?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=se($csrf)?>"><input type="hidden" name="action" value="assign_staff"><input type="hidden" name="user_id" value="<?=$u['id']?>"><div class="form-grid"><select name="staff_role"><?php foreach($roles as $key=>$rd):?><option value="<?=se($key)?>" <?=$u['staff_role']===$key?'selected':''?>><?=se($rd[0])?></option><?php endforeach;?></select><div class="perms"><?php foreach($permLabels as $pk=>$pl):?><label><input type="checkbox" name="permissions[]" value="<?=se($pk)?>" <?=in_array($pk,$current,true)?'checked':''?>> <?=se($pl)?></label><?php endforeach;?></div><button class="btnx">Assign / Update</button></div></form><?php endif;?></td><td><?php if($u['admin_role']!=='super_admin'&&$u['staff_role']):?><form method="post"><input type="hidden" name="csrf" value="<?=se($csrf)?>"><input type="hidden" name="user_id" value="<?=$u['id']?>"><?php if($u['admin_role']==='admin'&&$u['admin_enabled']):?><input type="hidden" name="action" value="disable_staff"><button class="btnx danger">Disable admin</button><?php else:?><input type="hidden" name="action" value="enable_staff"><button class="btnx">Enable admin</button><?php endif;?></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></section>
<section class="panel"><h2>Permission model</h2><table class="table"><thead><tr><th>Role</th><th>Default permissions</th></tr></thead><tbody><?php foreach($roles as $r):?><tr><td><b><?=se($r[0])?></b></td><td><?=se(implode(' · ',array_map(fn($x)=>$permLabels[$x]??$x,$r[1])))?></td></tr><?php endforeach;?></tbody></table></section>
<section class="panel"><h2>Administrative audit log</h2><table class="table"><thead><tr><th>Date</th><th>Administrator</th><th>Action</th><th>Target</th></tr></thead><tbody><?php if(!$logs):?><tr><td colspan="4">No administrative changes recorded yet.</td></tr><?php endif;?><?php foreach($logs as $l):?><tr><td><?=se($l['created_at'])?></td><td><?=se($l['admin_name']?:'System')?></td><td><?=se(str_replace('_',' ',$l['action']))?></td><td><?=se($l['target_name']?:'—')?></td></tr><?php endforeach;?></tbody></table></section></main></body></html>