<?php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
function up_db(){static $p=null;if($p)return $p;$p=new PDO('mysql:host='.(getenv('DB_HOST')?:'127.0.0.1').';port='.(getenv('DB_PORT')?:'3306').';dbname='.(getenv('DB_NAME')?:'datasell').';charset=utf8mb4',getenv('DB_USER')?:'root',getenv('DB_PASS')?:'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);return $p;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function up_csrf(){if(empty($_SESSION['upgrade_csrf']))$_SESSION['upgrade_csrf']=bin2hex(random_bytes(24));return $_SESSION['upgrade_csrf'];}
function up_check(){if(!hash_equals($_SESSION['upgrade_csrf']??'',$_POST['csrf']??''))throw new Exception('Session expired. Refresh and try again.');}
if(empty($_SESSION['uid'])){header('Location:/?page=login');exit;}
$q=up_db()->prepare('SELECT id,fullname,email,account_type,customer_tier,business_name,admin_role FROM users WHERE id=?');$q->execute([$_SESSION['uid']]);$u=$q->fetch();if(!$u){session_destroy();header('Location:/?page=login');exit;}
function current_tier($u){if($u['account_type']==='reseller')return 'Reseller';if($u['account_type']==='api')return 'API User';return $u['customer_tier']==='premium'?'Premium Customer':'Standard Customer';}
$msg='';$err='';
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){
  up_check();$tier=$_POST['requested_tier']??'';
  if(!in_array($tier,['premium','reseller','api'],true))throw new Exception('Choose a valid upgrade tier.');
  $exists=up_db()->prepare("SELECT COUNT(*) FROM upgrade_requests WHERE user_id=? AND status='pending'");$exists->execute([$u['id']]);if((int)$exists->fetchColumn()>0)throw new Exception('You already have a pending upgrade request.');
  $b=trim($_POST['business_name']??'');$reason=trim($_POST['reason']??'');
  if(in_array($tier,['reseller','api'],true)&&strlen($b)<2)throw new Exception('Enter your business or brand name for Reseller/API access.');
  up_db()->prepare('INSERT INTO upgrade_requests(user_id,requested_tier,business_name,reason) VALUES(?,?,?,?)')->execute([$u['id'],$tier,$b?:null,$reason?:null]);
  $msg='Your upgrade request has been submitted for administrator approval.';
 }
}catch(Throwable $x){$err=$x->getMessage();}
$csrf=up_csrf();$hist=up_db()->prepare('SELECT * FROM upgrade_requests WHERE user_id=? ORDER BY id DESC LIMIT 20');$hist->execute([$u['id']]);$hist=$hist->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IHLink Datasub — Upgrade Account</title><link rel="stylesheet" href="/assets/css/app.css?v=6"><style>
body{background:#f5f7fb}.wrap{max-width:1100px;margin:auto;padding:32px 22px}.head{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:25px}.head h1{margin:5px 0}.current{background:#07111f;color:#fff;border-radius:18px;padding:18px 22px;margin-bottom:22px}.current span{color:#9eb0c5;font-size:12px}.current strong{display:block;font-size:26px;margin-top:4px}.tiers{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:20px 0}.tier{background:#fff;border:1px solid #e4e9f0;border-radius:18px;padding:22px}.tier h3{margin:4px 0 8px}.tier ul{padding-left:18px;color:#5e6b7c;line-height:1.8;font-size:13px}.tier.premium{border-color:#e8ca68}.tier.api{border-color:#82baf0}.formbox,.history{background:#fff;border:1px solid #e4e9f0;border-radius:18px;padding:22px;margin-top:18px}.field{margin-bottom:14px}.field label{display:block;font-size:12px;font-weight:800;margin-bottom:7px}.field input,.field select,.field textarea{width:100%;border:1px solid #dde4eb;border-radius:10px;padding:12px}.field textarea{min-height:100px;resize:vertical}.notice{padding:12px 14px;border-radius:10px;margin:12px 0}.ok{background:#eaf8f0;color:#137a4a}.bad{background:#fff0f0;color:#b52d2d}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:11px;border-bottom:1px solid #edf0f4}.badge{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eef2f6;font-size:11px;font-weight:800}.pending{background:#fff7df;color:#8a681c}.approved{background:#eaf8f0;color:#137a4a}.rejected{background:#fff0f0;color:#b52d2d}@media(max-width:800px){.tiers{grid-template-columns:1fr}.head{align-items:flex-start;flex-direction:column}}</style></head><body><main class="wrap"><header class="head"><div><span class="eyebrow">Account upgrade</span><h1>Choose your IHLink Datasub tier</h1><p>Commercial upgrades are reviewed by an administrator. They do not grant admin access.</p></div><a class="btn btn-ghost" href="/?page=profile">Back to Account</a></header>
<div class="current"><span>Current account</span><strong><?=h(current_tier($u))?></strong><small><?=h($u['email'])?></small></div>
<?php if($msg):?><div class="notice ok"><?=h($msg)?></div><?php endif;?><?php if($err):?><div class="notice bad"><?=h($err)?></div><?php endif;?>
<section class="tiers"><div class="tier premium"><span class="eyebrow">Premium</span><h3>Premium Customer</h3><ul><li>Priority access to promotional offers</li><li>Eligible for premium pricing/cashback policies</li><li>Priority support eligibility</li></ul></div><div class="tier"><span class="eyebrow">Business</span><h3>Reseller</h3><ul><li>Reseller dashboard</li><li>Reseller pricing</li><li>Purchase services for customers</li><li>API access eligibility</li></ul></div><div class="tier api"><span class="eyebrow">Developer</span><h3>API User</h3><ul><li>API dashboard and API keys</li><li>API-tier pricing</li><li>Build your own VTU website/app</li><li>Balance, plans and purchase endpoints</li></ul></div></section>
<section class="formbox"><h2>Request an upgrade</h2><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><div class="field"><label>Requested tier</label><select name="requested_tier" required><option value="premium">Premium Customer</option><option value="reseller">Reseller</option><option value="api">API User</option></select></div><div class="field"><label>Business / brand name</label><input name="business_name" value="<?=h($u['business_name'])?>" placeholder="Required for Reseller or API"></div><div class="field"><label>Why do you want this upgrade?</label><textarea name="reason" placeholder="Tell us briefly about your usage or business."></textarea></div><button class="btn btn-primary">Submit upgrade request</button></form></section>
<section class="history"><h2>Upgrade history</h2><table class="table"><thead><tr><th>Tier</th><th>Status</th><th>Requested</th><th>Admin note</th></tr></thead><tbody><?php if(!$hist):?><tr><td colspan="4">No upgrade requests yet.</td></tr><?php endif;?><?php foreach($hist as $r):?><tr><td><?=h(ucfirst($r['requested_tier']))?></td><td><span class="badge <?=h($r['status'])?>"><?=h(ucfirst($r['status']))?></span></td><td><?=h($r['created_at'])?></td><td><?=h($r['review_note']?:'—')?></td></tr><?php endforeach;?></tbody></table></section>
</main></body></html>
